// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import Admin__SeatingChartForm__SeatController from "./admin/seating_chart_form/seat_controller"
application.register("admin--seating-chart-form--seat", Admin__SeatingChartForm__SeatController)

import Admin__SeatingChartForm__VenueLayoutController from "./admin/seating_chart_form/venue_layout_controller"
application.register("admin--seating-chart-form--venue-layout", Admin__SeatingChartForm__VenueLayoutController)

import Admin__SeatingChartFormController from "./admin/seating_chart_form_controller"
application.register("admin--seating-chart-form", Admin__SeatingChartFormController)

import DestroyableController from "./destroyable_controller"
application.register("destroyable", DestroyableController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)
