// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import Admin__SeatingChartForm__SeatController from "./admin/seating_chart_form/seat_controller"
application.register("admin--seating-chart-form--seat", Admin__SeatingChartForm__SeatController)

import Admin__SeatingChartForm__VenueLayoutController from "./admin/seating_chart_form/venue_layout_controller"
application.register("admin--seating-chart-form--venue-layout", Admin__SeatingChartForm__VenueLayoutController)

import Admin__SeatingChartFormController from "./admin/seating_chart_form_controller"
application.register("admin--seating-chart-form", Admin__SeatingChartFormController)

import DestroyableController from "./destroyable_controller"
application.register("destroyable", DestroyableController)

import DismissableController from "./dismissable_controller"
application.register("dismissable", DismissableController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import EaseOutController from "./ease_out_controller"
application.register("ease-out", EaseOutController)

import FileDropController from "./file_drop_controller"
application.register("file-drop", FileDropController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import PreviewController from "./preview_controller"
application.register("preview", PreviewController)

import SlideOverController from "./slide_over_controller"
application.register("slide-over", SlideOverController)
