version: '3'
services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bin/dev"
    volumes:
      - .:/var/www/dosey_doe_tickets
      - /var/www/dosey_doe_tickets/node_modules
      - bundle_cache:/var/www/dosey_doe_tickets/vendor/bundle
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - db
      - selenium
  selenium:
    image: selenium/standalone-chrome
    ports:
      - "7900:7900"
    environment:
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080
    volumes:
      - /dev/shm:/dev/shm

volumes:
  postgres_data:
  bundle_cache:
