version: '3'

services:
  app:
    build: .
    command: bin/dev
    tty: true
    volumes:
      - .:/app
      - bundle_cache:/bundle/vendor
      - bundle_bin:/bundle/bin
      - node_modules:/app/node_modules
      - storage:/app/storage
    environment:
      - BUNDLE_PATH=/bundle/vendor
      - BUNDLE_BIN=/bundle/bin
    ports:
      - "3000:3000"
    depends_on:
      - db
      - selenium
      - redis

  worker:
    build: .
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - .:/app
      - bundle_cache:/bundle/vendor
      - bundle_bin:/bundle/bin
      - storage:/app/storage
    environment:
      - BUNDLE_PATH=/bundle/vendor
      - BUNDLE_BIN=/bundle/bin
    depends_on:
      - db
      - redis


  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dosey-doe-tickets
    ports:
        - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  selenium:
    image: selenium/standalone-chrome:latest
    ports:
      - "7900:7900"
    volumes:
      - /dev/shm:/dev/shm
    environment:
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080

  redis:
    image: redis:latest
    ports:
      - "6379:6379"


volumes:
  bundle_cache:
  bundle_bin:
  node_modules:
  pg_data:
  storage: