version: '3'

services:
  app:
    build: .
    command: bin/dev
    tty: true
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db
      - selenium

  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dosey-doe-tickets
    volumes:
      - pg_data:/var/lib/postgresql/data

  selenium:
    image: selenium/standalone-chrome:latest
    ports:
      - "7900:7900"
    volumes:
      - /dev/shm:/dev/shm

volumes:
  bundle_cache:
  node_modules:
  pg_data: