databases:
  - name: dosey_doe_tickets
    databaseName: dosey_doe_tickets
    user: dosey_doe_tickets
    plan: free

services:
  - type: web
    plan: free
    name: dosey_doe_tickets
    env: Docker
    dockerfilePath: Dockerfile
    dockerCommand: "bundle exec puma -C config/puma.rb"
    numInstances: 1
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: dosey_doe_tickets
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false