default: &defaults
  push_api_key: <%= Rails.application.credentials.dig(:app_signal, :push_api_key) %>
  name: "Dosey Doe Tickets V2"

  ignore_namespaces:
    - action_cable

  # Errors that should not be recorded by AppSignal
  # For more information see our docs:
  # https://docs.appsignal.com/ruby/configuration/ignore-errors.html
  # ignore_errors:
  #   - Exception
  #   - NoMemoryError
  #   - ScriptError
  #   - LoadError
  #   - NotImplementedError
  #   - SyntaxError
  #   - SecurityError
  #   - SignalException
  #   - Interrupt
  #   - SystemExit
  #   - SystemStackError

  # See https://docs.appsignal.com/ruby/configuration/options.html for
  # all configuration options.

production:
  <<: *defaults
  active: true
