default: &defaults
  push_api_key: <%= Rails.application.credentials.dig(:app_signal, :push_api_key) %>
  name: "Tix"
  ignore_namespaces:
    - "action_cable"
  ignore_actions:
    - "Rails::HealthController#show"
  log_level: "error"

development:
  <<: *defaults
  active: false

production:
  <<: *defaults
  active: true
