development:
  adapter: postgresql
  url: postgresql://postgres:password@localhost:5432/dosey-doe-tickets_development

test:
  adapter: test

production:
  adapter: postgresql
  url: postgresql://dosey_doe_tickets:<%= ENV["POSTGRES_PASSWORD"] %>@<%= ENV["DB_HOST"] %>:5432/dosey_doe_tickets
  channel_prefix: dosey_doe_tickets_production
