default: &default
  adapter: sqlite3
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 10 }.to_i %>
  retries: 100
  default_transaction_mode: immediate

cache: &cache
  <<: *default
  migrations_paths: "db/cache/migrate"

jobs: &jobs
  <<: *default
  migrations_paths: "db/jobs/migrate"

development:
  primary:
    <<: *default
    database: db/data/dosey-doe-tickets_development.sqlite3
  jobs:
    <<: *jobs
    database: db/data/dosey-doe-tickets_jobs_development.sqlite3
  cache:
    <<: *cache
    database: db/data/dosey-doe-tickets_cache_development.sqlite3

test:
  primary:
    <<: *default
    database: db/data/dosey-doe-tickets_test.sqlite3

production:
  primary:
    <<: *default
    database: db/data/dosey_doe_tickets.sqlite3
  cache:
    <<: *cache
    database: db/data/dosey_doe_tickets_cache.sqlite3
  jobs:
    <<: *jobs
    database: db/data/dosey_doe_tickets_jobs.sqlite3
