default: &default
  adapter: sqlite3
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 10 }.to_i %>
  timeout: 15000
  retries: 500000

cache: &cache
  <<: *default
  migrations_paths: "db/cache/migrate"

jobs: &jobs
  <<: *default
  migrations_paths: "db/jobs/migrate"

development:
  primary:
    <<: *default
    database: db/data/dosey-doe-tickets_development.sqlite3
  jobs:
    <<: *jobs
    database: db/data/dosey-doe-tickets_jobs_development.sqlite3
  cache:
    <<: *cache
    database: db/data/dosey-doe-tickets_cache_development.sqlite3
  # POSTMIGRATION: Remove
  og:
    adapter: postgresql
    encoding: unicode
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    host: localhost
    username: postgres
    password:
    database: og_dd_tickets
    database_tasks: false
    gssencmode: disable

test:
  primary:
    <<: *default
    database: db/data/dosey-doe-tickets_test.sqlite3

production:
  primary:
    <<: *default
    database: data/dosey_doe_tickets.sqlite3
  cache:
    <<: *cache
    database: data/dosey_doe_tickets_cache.sqlite3
  jobs:
    <<: *jobs
    database: data/dosey_doe_tickets_jobs.sqlite3
  # POSTMIGRATION: Remove
  og:
    adapter: postgresql
    encoding: unicode
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    host: localhost
    username: postgres
    password:
    database: og_dd_tickets
    database_tasks: false
    gssencmode: disable
