default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

local: &local
  <<: *default
  host: db
  username: postgres
  password: password

development:
  <<: *local
  database: dosey-doe-tickets_development

test:
  <<: *local
  database: dosey-doe-tickets_test

production:
  <<: *default
  host: <%= ENV["DB_HOST"] %>
  username: dosey_doe_tickets
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  database: dosey_doe_tickets
