default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  password:
  username: postgres

development:
  <<: *default
  database: dosey-doe-tickets_development

test:
  <<: *default
  database: dosey-doe-tickets_test

production:
  <<: *default
  database: your_app_production
  username: your_production_username
  password: <%= ENV['YOUR_APP_DATABASE_PASSWORD'] %>
