default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 10 }.to_i %>
  port: 5432

local: &local
  <<: *default
  password: password
  user: postgres
  host: localhost

development:
  <<: *local
  database: tix_development

test:
  <<: *local
  database: tix_test

production:
  <<: *default
  database: tix_production
  host: <%= ENV["DB_HOST"] %>
  user: tix
  password: <%= ENV["POSTGRES_PASSWORD"] %>
