default: &default
  adapter: sqlite3
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 }.to_i %>
  timeout: 5000

local: &local
  <<: *default

cache: &cache
  migrations_paths: "db/cache/migrate"

jobs: &jobs
  migrations_paths: "db/jobs/migrate"

development:
  primary:
    <<: *local
    database: db/data/dosey-doe-tickets_development.sqlite3
  jobs:
    <<: *local
    <<: *jobs
    database: db/data/dosey-doe-tickets-jobs_development.sqlite3
  cache:
    <<: *local
    <<: *cache
    database: db/data/dosey-doe-tickets-cache_development.sqlite3
  # POSTMIGRATION: Remove
  og:
    adapter: postgresql
    encoding: unicode
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    host: localhost
    username: postgres
    password:
    database: og_dd_tickets
    database_tasks: false
    gssencmode: disable

test:
  primary:
    <<: *local
    database: db/data/dosey-doe-tickets_test.sqlite3

production_default: &production_default
  <<: *default

production:
  primary:
    <<: *production_default
    database: data/dosey_doe_tickets.sqlite3
  cache:
    <<: *production_default
    <<: *cache
    database: data/dosey_doe_tickets_cache.sqlite3
  jobs:
    <<: *production_default
    <<: *jobs
    database: data/dosey_doe_tickets_jobs.sqlite3
  # POSTMIGRATION: Remove
  og:
    adapter: postgresql
    encoding: unicode
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    host: localhost
    username: postgres
    password:
    database: og_dd_tickets
    database_tasks: false
    gssencmode: disable
