default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 }.to_i %>

local: &local
  <<: *default
  host: db
  username: postgres
  password: password

cache: &cache
  migrations_paths: "db/cache/migrate"

development:
  primary:
    <<: *local
    database: dosey-doe-tickets_development
  cache:
    <<: *local
    <<: *cache
    database: dosey-doe-tickets-cache_development

test:
  primary:
    <<: *local
    database: dosey-doe-tickets_test

production_default: &production_default
  <<: *default
  username: dosey_doe_tickets
  host: <%= ENV['DB_HOST'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

production:
  primary:
    <<: *production_default
    database: dosey_doe_tickets
  cache:
    <<: *production_default
    <<: *cache
    database: dosey_doe_tickets_cache
