service: tix
image: ryanvasichko/tix
registry:
  server: ghcr.io
  username: ryanvasichko@gmail.com
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  clear:
    RAILS_SERVE_STATIC_FILES: 1
    WEB_CONCURRENCY: 0
    RAILS_MAX_THREADS: 3
    HOST: tix.ryanvasichko.com
  secret:
    - RAILS_MASTER_KEY

builder:
  arch: amd64

ssh:
  user: deploy

volumes:
  - "/var/lib/tix/storage:/rails/storage"
  - "/var/lib/tix/log:/rails/log"

servers:
  web:
    hosts:
      - <%= ENV.fetch("TIX_HOST_IP") %>
    cmd: "bundle exec thrust ./bin/rails server"
  worker:
    hosts:
      - <%= ENV.fetch("TIX_HOST_IP") %>
    cmd: "bundle exec rake solid_queue:start"

proxy:
  host: "tix.ryanvasichko.com"
  app_port: 3000
  ssl: true
