service: tix
image: ryanvasichko/tix
registry:
  server: ghcr.io
  username: ryanvasichko@gmail.com
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  clear:
    RAILS_SERVE_STATIC_FILES: 1
    WEB_CONCURRENCY: 0
    RAILS_MAX_THREADS: 3
    HOST: <%= ENV.fetch("HOST") %>
  secret:
    - RAILS_MASTER_KEY

builder:
  local:
    arch: amd64

volumes:
  - "/var/lib/tix/storage:/rails/storage"
  - "/var/lib/tix/log:/rails/log"

servers:
  web:
    hosts:
      - <%= ENV.fetch("HOST") %>
    cmd: "bin/rails server"
    labels:
      traefik.http.routers.web.entrypoints: websecure
      traefik.http.routers.web.rule: Host(`tix.ryanvasichko.com`)
      traefik.http.routers.web.tls.certresolver: letsencrypt
      traefik.http.routers.web.middlewares: compression
  worker:
    hosts:
      - <%= ENV.fetch("HOST") %>
    cmd: "bundle exec rake solid_queue:start"

traefik:
  options:
    publish:
      - "443:443"
    volume:
      - "/letsencrypt/acme.json:/letsencrypt/acme.json" # To save the configuration file.
  labels:
    traefik.http.middlewares.compression.compress: true

  args:
    entryPoints.web.address: ":80"
    entryPoints.websecure.address: ":443"
    entryPoints.web.http.redirections.entryPoint.to: websecure
    entryPoints.web.http.redirections.entryPoint.scheme: https
    entryPoints.web.http.redirections.entrypoint.permanent: true
    entrypoints.websecure.http.tls: true
    entrypoints.websecure.http.tls.domains[0].main: "tix.ryanvasichko.com"
    certificatesResolvers.letsencrypt.acme.email: "fake_email@pleasedontspammepleaseplease.com"
    certificatesResolvers.letsencrypt.acme.storage: "/letsencrypt/acme.json"
    certificatesResolvers.letsencrypt.acme.httpchallenge: true
    certificatesResolvers.letsencrypt.acme.httpchallenge.entrypoint: web
