service: dosey_doe_tickets
image: ryanvasichko/dosey-doe-tickets

servers:
  web:
    hosts:
      - 24.199.102.17
    cmd: "./bin/rails server"
    labels:
      traefik.http.routers.web.entrypoints: websecure
      traefik.http.routers.web.rule: Host(`dd-tickets-v2.ryanvasichko.com`)
      traefik.http.routers.web.tls.certresolver: letsencrypt
      traefik.http.routers.web.middlewares: compression
  job:
    hosts:
      - 24.199.118.95
    cmd: bundle exec good_job start

registry:
  server: ghcr.io
  username: ryanvasichko@gmail.com
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  clear:
    DB_HOST: 137.184.40.18
    RAILS_SERVE_STATIC_FILES: 1
    RUBY_YJIT_ENABLE: 1
    WEB_CONCURRENCY: 0
  secret:
    - POSTGRES_PASSWORD
    - RAILS_MASTER_KEY

builder:
  multiarch: false
  args:
    RAILS_MASTER_KEY: <%= ENV["RAILS_MASTER_KEY"] %>

accessories:
  db:
    image: postgres:16
    host: 137.184.40.18
    port: 5432
    env:
      secret:
        - POSTGRES_PASSWORD
      clear:
        POSTGRES_USER: 'dosey_doe_tickets'
        POSTGRES_DB: 'dosey_doe_tickets_production'
    volumes:
      - "/mnt/postgres/data:/var/lib/postgresql/data"
  redis:
    image: redis:latest
    host: 137.184.40.18
    port: 6379
    volumes:
      - "/mnt/redis/data:/data"

traefik:
  options:
    publish:
      - "443:443"
      - "8080:8080"
    volume:
      - "/letsencrypt/acme.json:/letsencrypt/acme.json" # To save the configuration file.
  labels:
    traefik.http.middlewares.compression.compress: true
    
  args:
    entryPoints.web.address: ":80"
    entryPoints.websecure.address: ":443"
    entryPoints.web.http.redirections.entryPoint.to: websecure
    entryPoints.web.http.redirections.entryPoint.scheme: https
    entryPoints.web.http.redirections.entrypoint.permanent: true
    entrypoints.websecure.http.tls: true
    entrypoints.websecure.http.tls.domains[0].main: "dd-tickets-v2.ryanvasichko.com"
    certificatesResolvers.letsencrypt.acme.email: "fake_email@pleasedontspammepleaseplease.com"
    certificatesResolvers.letsencrypt.acme.storage: "/letsencrypt/acme.json"
    certificatesResolvers.letsencrypt.acme.httpchallenge: true
    certificatesResolvers.letsencrypt.acme.httpchallenge.entrypoint: web