service: dosey_doe_tickets
image: rvasichko/dosey_doe_tickets

servers:
  web:
    hosts:
      - 137.184.44.229
    cmd: "./bin/rails server"
    labels:
      traefik.http.routers.blog.entrypoints: websecure
      traefik.http.routers.blog.rule: Host(`dosey-doe-tickets-v2.ryanvasichko.com`)
      traefik.http.routers.blog.tls.certresolver: letsencrypt
#  job:
#    hosts:
#      - 137.184.44.229
#    cmd: bundle exec good_job start

registry:
  username: rvasichko
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  clear:
    DB_HOST: 137.184.44.229
    RAILS_SERVE_STATIC_FILES: 1
    RUBY_YJIT_ENABLE: 1
    WEB_CONCURRENCY: 0
    GOOD_JOB_MAX_THREADS: 1

builder:
  multiarch: false
  args:
    RAILS_MASTER_KEY: <%= ENV["RAILS_MASTER_KEY"] %>

accessories:
  db:
    image: postgres:16
    host: 137.184.44.229
    port: 5432
    env:
      secret:
        - POSTGRES_PASSWORD
      clear:
        POSTGRES_USER: 'dosey_doe_tickets'
        POSTGRES_DB: 'dosey_doe_tickets_production'
    directories:
      - data:/var/lib/postgresql/data

traefik:
  options:
    publish:
      - "443:443"
    volume:
      - "/letsencrypt/acme.json:/letsencrypt/acme.json" # To save the configuration file.
  args:
    entryPoints.web.address: ":80"
    entryPoints.websecure.address: ":443"
    entryPoints.web.http.redirections.entryPoint.to: websecure
    entryPoints.web.http.redirections.entryPoint.scheme: https
    entryPoints.web.http.redirections.entrypoint.permanent: true
    entrypoints.websecure.http.tls: true
    entrypoints.websecure.http.tls.domains[0].main: "dosey-doe-tickets-v2.ryanvasichko.com"
    certificatesResolvers.letsencrypt.acme.email: "fake_email@pleasedontspammepleaseplease.com"
    certificatesResolvers.letsencrypt.acme.storage: "/letsencrypt/acme.json"
    certificatesResolvers.letsencrypt.acme.httpchallenge: true
    certificatesResolvers.letsencrypt.acme.httpchallenge.entrypoint: web