service: dosey_doe_tickets
image: ryanvasichko/dosey-doe-tickets
registry:
  server: ghcr.io
  username: ryanvasichko@gmail.com
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  clear:
    DB_HOST: 5.161.114.209
    RAILS_SERVE_STATIC_FILES: 1
    WEB_CONCURRENCY: 2
    RAILS_MAX_THREADS: 3
    HOST: dosey-doe-tickets-v2.ryanvasichko.com
  secret:
    - RAILS_MASTER_KEY

builder:
  multiarch: <%= ENV.fetch("MULTIARCH", "true") == "true" %>

volumes:
  - "/var/lib/dosey-doe-tickets/db:/rails/db/data"

servers:
  web:
    hosts:
      - 5.161.114.209
    cmd: "./bin/rails server"
    labels:
      traefik.http.routers.web.entrypoints: websecure
      traefik.http.routers.web.rule: Host(`dosey-doe-tickets-v2.ryanvasichko.com`)
      traefik.http.routers.web.tls.certresolver: letsencrypt
      traefik.http.routers.web.middlewares: compression
  worker:
    hosts:
      - 5.161.114.209
    cmd: "bundle exec rake solid_queue:start"

accessories:
  redis:
    image: redis:latest
    host: 5.161.114.209
    port: 6379
    directories:
      - "data:/data"
  netdata:
    image: netdata/netdata:stable
    host: 5.161.114.209
    volumes:
      - "netdataconfig:/etc/netdata"
      - "netdatalib:/var/lib/netdata"
      - "netdatacache:/var/cache/netdata"
      - "/etc/passwd:/host/etc/passwd:ro"
      - "/etc/group:/host/etc/group:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "/proc:/host/proc:ro"
      - "/sys:/host/sys:ro"
      - "/etc/os-release:/host/etc/os-release:ro"
      - "/var/log:/host/var/log:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    env:
      clear:
        NETDATA_CLAIM_TOKEN: QC00DAglr-1OS8d_GClrO4khD1dPMDKW57EN2JsY8K0HSfHvCuV1SlnnO106GYRzPE4nspLeK-2l2V8p4xwkecLc9u3xHXByIkV2JZb3kknMqFhISr_FJ0HH0FtSAEQHKAk6zzY
        NETDATA_CLAIM_URL: https://app.netdata.cloud
        NETDATA_CLAIM_ROOMS: d0e3ed12-620e-4b4b-b2fc-584bb58486bb
    options:
      pid: host
      network: host
      cap-add:
        - SYS_PTRACE
        - SYS_ADMIN
      security-opt: apparmor=unconfined

traefik:
  options:
    publish:
      - "443:443"
    volume:
      - "/letsencrypt/acme.json:/letsencrypt/acme.json" # To save the configuration file.
  labels:
    traefik.http.middlewares.compression.compress: true

  args:
    entryPoints.web.address: ":80"
    entryPoints.websecure.address: ":443"
    entryPoints.web.http.redirections.entryPoint.to: websecure
    entryPoints.web.http.redirections.entryPoint.scheme: https
    entryPoints.web.http.redirections.entrypoint.permanent: true
    entrypoints.websecure.http.tls: true
    entrypoints.websecure.http.tls.domains[0].main: "dosey-doe-tickets-v2.ryanvasichko.com"
    certificatesResolvers.letsencrypt.acme.email: "fake_email@pleasedontspammepleaseplease.com"
    certificatesResolvers.letsencrypt.acme.storage: "/letsencrypt/acme.json"
    certificatesResolvers.letsencrypt.acme.httpchallenge: true
    certificatesResolvers.letsencrypt.acme.httpchallenge.entrypoint: web
