service: dosey_doe_tickets
image: ryanvasichko/dosey-doe-tickets

servers:
  web:
    hosts:
      - 5.161.114.209
    cmd: "./bin/rails server"
    labels:
      traefik.http.routers.web.entrypoints: websecure
      traefik.http.routers.web.rule: Host(`dosey-doe-tickets-v2.ryanvasichko.com`)
      traefik.http.routers.web.tls.certresolver: letsencrypt
      traefik.http.routers.web.middlewares: compression
    options:
      volume: "/mnt/volume_1/db:/rails/data"
  worker:
    hosts:
      - 5.161.114.209
    cmd: "bundle exec rake solid_queue:start"
    options:
      volume: "/mnt/volume_1/db:/rails/data"


registry:
  server: ghcr.io
  username: ryanvasichko@gmail.com
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  clear:
    DB_HOST: 5.161.114.209
    RAILS_SERVE_STATIC_FILES: 1
    WEB_CONCURRENCY: 2
  secret:
    - RAILS_MASTER_KEY

builder:
  multiarch: <%= ENV.fetch("MULTIARCH", "true") == "true" %>

accessories:
  redis:
    image: redis:latest
    host: 5.161.114.209
    port: 6379
    directories:
      - "data:/data"

traefik:
  options:
    publish:
      - "443:443"
    volume:
      - "/letsencrypt/acme.json:/letsencrypt/acme.json" # To save the configuration file.
  labels:
    traefik.http.middlewares.compression.compress: true

  args:
    entryPoints.web.address: ":80"
    entryPoints.websecure.address: ":443"
    entryPoints.web.http.redirections.entryPoint.to: websecure
    entryPoints.web.http.redirections.entryPoint.scheme: https
    entryPoints.web.http.redirections.entrypoint.permanent: true
    entrypoints.websecure.http.tls: true
    entrypoints.websecure.http.tls.domains[0].main: "dosey-doe-tickets-v2.ryanvasichko.com"
    certificatesResolvers.letsencrypt.acme.email: "fake_email@pleasedontspammepleaseplease.com"
    certificatesResolvers.letsencrypt.acme.storage: "/letsencrypt/acme.json"
    certificatesResolvers.letsencrypt.acme.httpchallenge: true
    certificatesResolvers.letsencrypt.acme.httpchallenge.entrypoint: web
