default: &default
  database: cache
  store_options:
    max_age: <%= 6.weeks.to_i %>
    max_size: <%= 256.megabytes %>
    namespace: <%= Rails.env %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
