default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
      recurring_tasks:
        destroy_inactive_guests:
          class: Users::Guest::DestroyInactiveJob
          schedule: every day at midnight
  workers:
    - queues: "*"
      threads: 2
      processes: 1
      polling_interval: 0.1

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
